
server:
  port: 5000
  servlet:
    context-path: /uaa
spring:
  application:
    name: service-auth
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-security?useUnicode=true&characterEncoding=utf-8&characterSetResult=utf-8
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
security:
  oauth2:
    resource:
      filter-order: 3
eureka:
  client:
    service-url:
      defaultzone: http://10.2.72.112:8761/eureka/

